language: node_js

node_js:
 - 10.15.3

cache:
  directories:
    - ./client/node_modules
    - ./server/node_modules

before_script:
  - npm install --prefix client

script:
  - npm run test-hook --prefix client
